# -*- coding: utf-8 -*-
"""Copy of sidequest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r2lPfd3oqddrpodFXMT-q6FGBho5Kez6
"""

import pandas as pd
import numpy as np

data = pd.read_excel('/content/weather_dataset_stage1.xlsx')

data.head()

data.shape

data.dtypes

data.isnull().sum()

data.isin(['?']).sum()

data[['Date','Date1']]

data = data.drop(['Date1'], axis=1)
data.head()

for i in range(1,len(data.columns)):
  for j in range(len(data.iloc[:,i])):
    data.iloc[:,i][j]=float(data.iloc[:,i][j].strip("';"))

#for i in range(1,len(data.columns)):

data

print(data.columns.tolist())

for i in data.columns:
  data.rename({i:i.strip(" ").strip("(").replace(" ",'_').replace("(","_")}, axis = 1, inplace = True)

print(data.columns.tolist())

for i in range(len(data['Date'])):
  data['Date'][i] = data['Date'][i].strip(" '").replace("-","/")

data.Date

data[['year','month','day']] = data.Date.str.split("/",expand=True)

data[data['Date']=='2022/01/01']

for i in range(3692,3903):
  if i == 3751:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2033")

for i in range(3333,3692):
  if i == 3751:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2032")

for i in range(3009,3333):
  if i == 3751:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2031")

for i in range(2673,3009):
  if i == 3751:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2030")

for i in range(2307,2673):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2029")

for i in range(1956,2307):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2028")

for i in range(1599,1956):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2027")

for i in range(1279,1599):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2026")

for i in range(942,1279):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2025")

for i in range(692,942):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2024")

for i in range(331,692):
  if i == 2366:
    continue
  data['Date'][i]=data['Date'][i].replace("2022","2023")

data['Date'][2366]=data['Date'][2366].replace("2022","2028")
data['Date'][3751]=data['Date'][3751].replace("2022","2032")

data['Date']=pd.to_datetime(data['Date'])

data = data.sort_values('Date')

data

data.to_excel("ha1.xlsx")

